/**
 * Sun Walk domain types — the contract.
 *
 * Copy to src/domain/types.ts. This file must not import anything.
 *
 * Rules:
 *  - Every cross-object reference is an id, never an embedded object.
 *  - Coordinates are [longitude, latitude], WGS84, 6 decimal places.
 *  - Distances are meters, in fields ending `M`. Durations are seconds, `Sec`.
 *  - Nothing here knows MapLibre exists.
 */

export type EntityId = string;
export type Position = [lon: number, lat: number];

export type EntityKind =
  | "building"
  | "node"
  | "edge"
  | "route"
  | "closure"
  | "session";

/* ------------------------------------------------------------------ */
/* Building                                                            */
/* ------------------------------------------------------------------ */

/** From UFRM layer 0 `Type`. Never inferred from floor area. */
export type BuildingCategory =
  | "academic"
  | "administrative"
  | "athletics"
  | "fine-arts"
  | "housing"
  | "library"
  | "research"
  | "student-services"
  | "parking"
  | "support"
  | "unknown";

export type Building = {
  kind: "building";
  id: EntityId;                 // `bldg:{CODE}` or `bldg:{CODE}#2` for split duplicates
  code: string;                 // UFRM BLDG_CODE, uppercase
  /** UFRM BLDG_NAME verbatim, ALL CAPS. Never shown to users. */
  officialName: string;
  /** What students call it. From overlays/name-overrides.json, falls back to officialName. */
  displayName: string;
  category: BuildingCategory;
  centroid: Position;
  /** Key into build/footprints.geojson. Null when no polygon exists. */
  footprintId: EntityId | null;
  footprintSource: "ufrm" | "campus" | "proxy" | "none";
  /** Ordered; index 0 is the preferred main entrance. May be empty. */
  entranceIds: EntityId[];
  gsf: number | null;
  address: string | null;
  imageUrl: string | null;      // UFRM layer 0 `Image`
  inServiceArea: boolean;
  /** Computed: inServiceArea && entranceIds.length > 0 && reachable from the main component. */
  routable: boolean;
  unroutableReason: RouteFailure | null;
};

/* ------------------------------------------------------------------ */
/* Graph                                                               */
/* ------------------------------------------------------------------ */

export type NodeType = "walkway" | "entrance" | "crossing";

export type GraphNode = {
  kind: "node";
  id: EntityId;                 // `node:{base32 hash}` — content-derived, never positional
  type: NodeType;
  position: Position;
  /** Debug label only. Never used for identity or display. */
  label?: string;

  // entrance only
  buildingId?: EntityId;
  /** true = builder-projected candidate, not a surveyed door. */
  provisional?: boolean;
  /** true = projected at the 120 m fallback radius; low confidence. */
  weak?: boolean;
  entranceName?: string;        // "north", "main", "loading"

  // crossing only
  signalized?: boolean;
  crossingKind?: "traffic_signals" | "marked" | "unmarked";
};

export type Surface =
  | "paved" | "concrete" | "asphalt" | "gravel" | "grass" | "sand" | "unknown";

export type EdgeType = "path" | "steps" | "crossing" | "link" | "plaza" | "indoor";

export type ShadeSource =
  | "survey" | "covered" | "treerow" | "adjacency" | "default";

export type GraphEdge = {
  kind: "edge";
  id: EntityId;                 // `edge:{base32 hash}`
  type: EdgeType;
  fromNodeId: EntityId;
  toNodeId: EntityId;
  /** Full polyline. First == from node position, last == to node position. >= 2 positions. */
  geometry: Position[];
  /** Haversine sum along geometry. Computed by the builder, never hand-entered. */
  lengthM: number;

  /** Path name where known ("Palm Walk", "Cady Mall"). Drives leg instructions. */
  name: string | null;
  surface: Surface;
  stairs: boolean;
  stepCount: number | null;
  covered: boolean;
  indoor: boolean;
  /** true = wheelchair passable, false = known not, null = unknown. */
  accessible: boolean | null;
  /** 0 = full sun, 1 = full shade. */
  shadeIndex: number;
  shadeSource: ShadeSource;
  /** true when generated by plaza skeletonization rather than mapped geometry. */
  synthetic: boolean;

  /** Provenance for debugging and for licence attribution. */
  osmWayId: number | null;
};

/* ------------------------------------------------------------------ */
/* Closure — runtime overlay, not baked into the graph                 */
/* ------------------------------------------------------------------ */

export type Closure = {
  kind: "closure";
  id: EntityId;                 // `closure:{slug}`
  reason: string;
  /** ISO 8601. `to` null = indefinite. */
  from: string;
  to: string | null;
  edgeIds: EntityId[];
  nodeIds: EntityId[];
  sourceUrl: string | null;
};

/* ------------------------------------------------------------------ */
/* Routing                                                             */
/* ------------------------------------------------------------------ */

export type Profile = {
  id: string;                   // "walk-default" | "walk-accessible" | ...
  walkSpeedMps: number;
  avoidStairs: boolean;
  requireAccessible: boolean;
  /** 0 = ignore shade, 1 = strongly prefer shade. */
  shadeWeight: number;
  crossingPenaltySec: number;
};

export type RouteLeg = {
  edgeIds: EntityId[];
  instruction: string;
  distanceM: number;
  /** Degrees clockwise from true north at the start of the leg. */
  bearing: number;
};

export type Route = {
  kind: "route";
  id: EntityId;                 // `route:{fromNodeId}>{toNodeId}@{profileId}:{hourBucket}`
  fromBuildingId: EntityId;
  toBuildingId: EntityId;
  /** Which door the search actually chose. */
  fromNodeId: EntityId;
  toNodeId: EntityId;
  nodeIds: EntityId[];
  edgeIds: EntityId[];
  legs: RouteLeg[];
  lengthM: number;
  estimatedSec: number;
  profileId: string;
  /** Fraction of lengthM that is shaded, for the UI. */
  shadedFraction: number;
  /** Content hash of the graph this was computed against. Invalidation key. */
  graphHash: string;
};

export type RouteFailure =
  | "unknown_building"
  | "same_building"
  | "no_entrance"
  | "no_footprint"
  | "out_of_service_area"
  | "no_accessible_route"
  | "disconnected";

export type RouteResult =
  | { ok: true; route: Route }
  | { ok: false; reason: RouteFailure; detail?: string };

/* ------------------------------------------------------------------ */
/* Session                                                             */
/* ------------------------------------------------------------------ */

export type Session = {
  kind: "session";
  id: "session:local";
  originBuildingId: EntityId | null;
  destBuildingId: EntityId | null;
  activeRouteId: EntityId | null;
  /** Last routing failure, so the UI can explain itself. */
  lastFailure: RouteFailure | null;
  selectedId: EntityId | null;
  profileId: string;
  headingUp: boolean;
  showGraph: boolean;
};

export type Entity = Building | GraphNode | GraphEdge | Route | Closure | Session;

/* ------------------------------------------------------------------ */
/* Projection output                                                   */
/* ------------------------------------------------------------------ */

export type GeoJSONGeometry =
  | { type: "Point"; coordinates: Position }
  | { type: "LineString"; coordinates: Position[] }
  | { type: "Polygon"; coordinates: Position[][] };

export type GeoJSONFeatureCollection = {
  type: "FeatureCollection";
  features: Array<{
    type: "Feature";
    id?: string;
    geometry: GeoJSONGeometry;
    properties: Record<string, unknown>;
  }>;
};

/* ------------------------------------------------------------------ */
/* Build artifact                                                      */
/* ------------------------------------------------------------------ */

export type BuildManifest = {
  generatedUtc: string;
  builderGitRev: string;
  /** SHA-256 of every file under sources/ and overlays/. */
  inputs: Record<string, string>;
  /** Content hash of this graph. Used as Route.graphHash. */
  graphHash: string;
  counts: {
    buildings: number;
    routableBuildings: number;
    nodes: number;
    entrances: number;
    provisionalEntrances: number;
    crossings: number;
    edges: number;
    totalLengthM: number;
    components: number;
  };
};

export type GraphFile = {
  manifest: BuildManifest;
  buildings: Building[];
  nodes: GraphNode[];
  edges: GraphEdge[];
};
